version: "3.9"

services:
web:
  build: .
  command: gunicorn metro.wsgi:application --bind 0.0.0.0:8000
  env_file:
    - .env
  environment:
    DJANGO_SETTINGS_MODULE: metro.metro.settings
  depends_on:
    - db
